# Generated by Django 4.2.11 on 2024-05-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cloth_material_category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('url', models.CharField(max_length=400)),
                ('tags', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='casual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cloth_material_category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('url', models.CharField(max_length=400)),
                ('tags', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cloth_material_category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('url', models.CharField(max_length=400)),
                ('tags', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='formal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cloth_material_category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('url', models.CharField(max_length=400)),
                ('tags', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='kids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cloth_material_category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('url', models.CharField(max_length=400)),
                ('tags', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='occational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cloth_material_category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('url', models.CharField(max_length=400)),
                ('tags', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
